Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,7 +20,11 @@ jobs:
       run: |
         echo "$ENV_FILE" > .env
     - name: Check environment variable
-      run: echo $DATABASE_URL
+      run: |
+        if [[ -z $DATABASE_URL ]]; then
+          echo "Error: DATABASE_URL environment variable is empty"
+          exit 1
+        fi
         
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag medical-records-server
